// ⚠️ Auto-generated by svelte-server-function plugin
import * as mod0 from '$lib/server/get-user';
import * as mod1 from '$lib/server/get-session';

export const modules = {
  "$lib/server/get-user": mod0,
  "$lib/server/get-session": mod1,
};